server:
  port: 8083

spring:
  application:
    name: smartshopai-ai-analysis-service
  profiles:
    active: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: smartshopai
      username: smartshopai_user
      password: smartshopai_password
      authentication-database: smartshopai
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-dummy-key-for-development}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-4
          temperature: 0.7
          max-tokens: 1000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.smartshopai.ai.analysis: DEBUG
    org.springframework.ai: DEBUG
