server:
  port: 8080

spring:
  application:
    name: smartshopai-gateway
  profiles:
    active: docker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://smartshopai-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://smartshopai-product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: ai-analysis-service
          uri: lb://smartshopai-ai-analysis-service
          predicates:
            - Path=/api/ai/analysis/**
          filters:
            - StripPrefix=1
        - id: ai-recommendation-service
          uri: lb://smartshopai-ai-recommendation-service
          predicates:
            - Path=/api/ai/recommendations/**
          filters:
            - StripPrefix=1
        - id: ai-search-service
          uri: lb://smartshopai-ai-search-service
          predicates:
            - Path=/api/ai/search/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: lb://smartshopai-search-service
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://smartshopai-notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: monitoring-service
          uri: lb://smartshopai-monitoring
          predicates:
            - Path=/api/monitoring/**
          filters:
            - StripPrefix=1
        - id: business-intelligence-service
          uri: lb://smartshopai-business-intelligence-service
          predicates:
            - Path=/api/business-intelligence/**
          filters:
            - StripPrefix=1
        - id: cache-service
          uri: lb://smartshopai-cache-service
          predicates:
            - Path=/api/cache/**
          filters:
            - StripPrefix=1
        - id: session-cache-service
          uri: lb://smartshopai-session-cache-service
          predicates:
            - Path=/api/session-cache/**
          filters:
            - StripPrefix=1
        - id: security-service
          uri: lb://smartshopai-security
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=1
        - id: swagger-ui
          uri: http://localhost:8080
          predicates:
            - Path=/swagger-ui/**
          filters:
            - StripPrefix=0
        - id: api-docs
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
